name: widgetbook_ui
description: A Flutter project to manage design system.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  widgetbook: ^3.2.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.1.0

flutter:
  uses-material-design: true
